- name: install apache2
  become: yes
  apt:
    name: ['apache2']
    state: latest
  tags: [ apache ]

- name: start apache2
  service:
    name: apache2
    enabled: true
    state: started
  tags: [ apache ]

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags: [ apache ]

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache
  tags: [ apache ]
