- name: install mariadb
  apt:
    name:
      - libapache2-mod-fcgid
      - php8.0
      - php8.0-fpm
      - php8.0-mysql
      - php8.0-mbstring
      - php8.0-curl
      - php8.0-common
      - php8.0-mcrypt
    state: latest
