- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ wordpress ]

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"
  tags: [ wordpress ]

- name: Permissions and owners
  file: 
    dest: /var/www/{{ http_host }}/wordpress/
    owner: www-data
    group: www-data
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Fetch salt
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: 'wp_salt'
  tags: [ wordpress ]

- name: Set up wp-config
  template:
    src: "wp-config.php"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
  tags: [ wordpress ]

