- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ wordpress ]

- name: Download and unpack latest WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}wordpress"
  tags: [ wordpress ]

  #- name: Set permissions for directories
  #  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
  #  tags: [ wordpress ]
  #
  #- name: Set permissions for files
  #  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
  #  tags: [ wordpress ]
  #
  #- name: Set owner and group
  #  shell: "/usr/bin/chown -R www-data:www-data /var/www/;"
  #  tags: [ wordpress ]

- name: Permissions and owners
  file: 
    dest: /var/www/{{ http_host }}/wordpress/
    owner: www-data
    group: www-data
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Wordpresss | Fetch random salts for wp-config.php
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: 'wp_salt'
  tags: [ wordpress ]

- name: Set up wp-config
  template:
    src: "wp-config.php"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
  tags: [ wordpress ]

