#wp settings
wp_db_name: 'wordpress'
wp_db_user: 'wordpress'
wp_db_password: 'w0rdpr3$$'
wp_db_host: 'localhost'
wp_db_charset: 'utf8'
wp_db_collate: ''
wp_table_prefix: 'wp_'
wp_debug: false
wp_fs_method: 'direct'
wp_lang: ''

