---
# tasks file for ansible-role-wordpress

# required
- include: requirements.yml
# web
- include: nginx.yml
# mariadb
- include: mariadb.yml
# php
- include: php.yml
# wordpress
- include: wordpress.yml
# varnish
- include: varnish.yml
# certbot
# - include certbot
