- name: install what I like
  become: yes
  apt:
    name: ['mariadb-server', 'mariadb-client']
    update_cache: yes
    state: latest

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started

- name: Root password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

- name: remove remote root
  mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: "{{ ansible_fqdn }}"
    state: absent

#TODO CREATE WORDPRESS USER AND DATABASE
