---
- name: Install nginx
  become: yes
  apt:
    name: ['nginx']
    update_cache: yes
    state: latest
  tags: [ nginx ]

- name: Copy nginx configuration for wordpress
  template: src=nginx-site.conf dest=/etc/nginx/sites-enabled/default
  tags: [ nginx ]

- name: start nginx
  service:
    name: nginx
    enabled: true
    state: started
  tags: [ nginx ]
