---
- name: Install nginx
  become: yes
  apt:
    name: ['nginx']
    update_cache: yes
    state: latest
  tags: [ nginx ]

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/conf.d/default
  notify: Restart nginx
  tags: [ nginx ]

- name: Copy nginx configuration for wordpress
  template: src=nginx-site.conf dest=/etc/nginx/sites-enabled/wordpress.conf
  notify: Restart nginx
  tags: [ nginx ]

- name: Remove default nginx
  notify: Restart nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: start nginx
  service:
    name: nginx
    enabled: true
    state: started
  tags: [ nginx ]
