- apt_repository:
    repo: ppa:ondrej/php
    state: present
    tags: [ php ]

- name: Install PHP Extensions
    apt: 
      pkg:
        - php8.0
        - php8.0-zip
        - php8.0-intl
        - php8.0-soap
        - php8.0-xml
        - php8.0-xmlrcp
        - php8.0-gd
        - php8.0-fpm
        - php8.0-mysql
        - php8.0-mbstring
        - php8.0-curl
        - php8.0-common
        - php8.0-mcrypt
      update_cache: yes
      state: latest
    tags: [ php ]

- name: Enable php module
    shell: /usr/sbin/a2enconf php8.0-fpm
    notify: Reload Apache
    tags: [ apache ]
