---
- name: Install pymysql for mysql actions
  become: yes
  apt:
    name: ['pip3']
    state: present
  tags: [ required ]

- name: Install pymysql for mysql actions
  become: yes
  pip:
    name: ['pymysql']
    state: present
  tags: [ required ]

