---
- name: Install pip3 for python requirements
  become: yes
  apt:
    name: ['python3-pip']
    update_cache: yes
    state: present
  tags: [ required ]

- name: Install pymysql for mysql actions
  become: yes
  pip:
    name: ['pymysql']
    state: present
  tags: [ required ]

