---
- name: Install varnish
  become: yes
  apt:
    name: ['varnish']
    update_cache: yes
    state: latest
  tags: [ varnish ]

- name: default varnish
  template:
    src: "varnish-default.conf"
    dest: "/etc/default/varnish"
  tags: [ varnish ]

- name: varnish custom conf
  template:
    src: "varnish-custom.conf"
    dest: "/etc/varnish/custom.vcl"
  tags: [ varnish ]

- name: varnish service
  template:
    src: "varnish-service"
    dest: "/lib/systemd/system/varnish.service"
  tags: [ varnish ]

